
# This is currently needed to ensure openssl libraries are bundled into the
# cross compilation image
#
# This is due to the reqwest library being pulled in recent releases with
# default features enabled, including native-tls :(
[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
]
