[package]
name = "parquet-concat"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
bytes = { workspace = true }
lambda_runtime = { workspace = true }
oxbow = { path = "../../crates/oxbow" }
oxbow-lambda-shared = { path = "../../crates/oxbow-lambda-shared" }
oxbow-sqs = { path = "../../crates/oxbow-sqs" }

anyhow = { workspace = true }
aws_lambda_events = { workspace = true, default-features = false, features = ["sqs"] }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
deltalake = { workspace = true }
parquet = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
stats_alloc = "0.1"
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3.8"