[package]
name = "glue-sync"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
aws_lambda_events = { workspace = true }
deltalake = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

oxbow-lambda-shared = { path = "../../crates/oxbow-lambda-shared" }

aws-sdk-glue = { workspace = true }
aws-config = { workspace = true, features = ["behavior-version-latest"] }
lambda_runtime = { workspace = true }
