ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: macro

= CDF to CSV

The `cdf-to-csv` is an S3 Event Notifications triggered Lambda whose
responsibility is to read a link:https://delta.io[Delta Lake] table's change
data feed in order to produce CSV output for the changed rows which can be
imported into other systems via
link:https://dev.mysql.com/doc/refman/8.4/en/load-data.html[`LOAD DATA`] or
`LOAD DATA FROM S3`

toc::[]

== Output schema

Currently `cdf-to-csv` only supports insert/update files being generated. The
lambda will rely on the prefix of the Delta table being modified. For example,
if the source table is located at `s3://datalake/schemas/myschema/mytable` and
the `CSV_OUTPUT_URL` is set to `s3://csvs/` then the prefix tree for output
`.csv` files for table versions 3, 4, 5 should look like the following:

[source]
----
s3://csvs/
в”њв”Ђв”Ђ schemas
в”‚В В  в”њв”Ђв”Ђ myshema
в”‚В В  в”‚В В  в”њв”Ђв”Ђ mytable
в”‚В В  в”‚В В  в”‚В В  в”њв”Ђв”Ђ 3
в”‚В В  в”‚В В  в”‚В В  в”‚В В  в””в”Ђв”Ђ inserts
в”‚В В  в”‚В В  в”‚В В  в”‚В В      в”њв”Ђв”Ђ uuid_1.csv
в”‚В В  в”‚В В  в”‚В В  в”‚В В      в”њв”Ђв”Ђ uuid_2.csv
в”‚В В  в”‚В В  в”‚В В  в”њв”Ђв”Ђ 4
в”‚В В  в”‚В В  в”‚В В  в”‚В В  в””в”Ђв”Ђ inserts
в”‚В В  в”‚В В  в”‚В В  в”‚В В      в”њв”Ђв”Ђ uuid_1.csv
в”‚В В  в”‚В В  в”‚В В  в”‚В В      в”њв”Ђв”Ђ uuid_2.csv
в”‚В В  в”‚В В  в”‚В В  в”њв”Ђв”Ђ 5
----


== Environment Variables

|===

| Name | Default Value | Notes

| `CSV_OUTPUT_URL`
|
| Full destination URL for writing output CSV files, e.g. `s3://bucket/rootprefix`

| `DELETE_PRIMARY_KEY`
|
| Optional primary key for delete CSV files

| `CSV_BOOL_AS_INT`
|
| When this environment variable exists, any boolean `true` will be written as `1` in the CSV output. False and null values are both encoded as `0`.

| `CSV_DELETE_PREFIX`
|
| Prefix for output CSV files with deleted rows (requires primary key set)

| `CSV_NULL_CHARACTER`
|
| Character to use as the null character in CSV output

| `CSV_TIMESTAMP_FORMAT`
| `%Y-%m-%dT%H:%M:%S%.f`
| Format string for `timestamp` fields

| `CSV_TIMESTAMP_TZ_FORMAT`
|
| Timestamp format for timestamp with timezone arrays. When empty ISO 8601 format is used.

| `RUST_LOG`
| `error`
| Set the log level, e.g. `info`, `warn`, `error`. Can be scoped to specific modules, i.e. `oxbow=debug`

| `UNWRAP_SNS_ENVELOPE`
| _null_
| Should only be used if S3 Event Notifications are first going to SNS and then routing to SQS for Oxbow

|===
