/*
 * This Jenkinsfile is for internal use
 */

pipeline {
  agent none
  options {
    retry(1)
    // This timeout can include wait time when executors are occupied, so using
    // something arbitrarily high for the whole pipeline
    timeout(time: 6, unit: 'HOURS')
    parallelsAlwaysFailFast()
  }

  stages {
    stage('Check') {
      agent { label 'rust' }
      steps {
        sh 'cargo fmt --check'
      }
    }

    stage('Build') {
      options {
        timeout(time: 1, unit: 'HOURS')
      }
      parallel {
        stage('Crates - FreeBSD') {
          agent { label 'freebsd' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j2 -C crates build'
          }
        }

        stage('Crates - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C crates build'
          }
        }

        stage('Lambdas - FreeBSD') {
          agent { label 'freebsd' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j2 -C lambdas build'
          }
        }

        stage('Lambdas - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C lambdas build'
          }
        }
      }
    }

    stage('Test') {
      parallel {
        stage('Crates Test - FreeBSD') {
          agent { label 'freebsd' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j2 -C crates test'
          }
        }

        stage('Crates Test - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C crates test'
          }
        }

        stage('Lambdas Test - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C lambdas test'
          }
        }
      }
    }

    stage('Release') {
      agent { label 'linux' }
      when { branch 'main' }
      options {
        timeout(time: 2, unit: 'HOURS')
      }
      steps {
        sh './ci/build-release.sh'
        sh './ci/rename-artifacts.sh'
        archiveArtifacts artifacts: 'target/artifacts/*.zip', fingerprint: true, onlyIfSuccessful: true
      }
    }
  }
}

// vim: ft=groovy sw=2 ts=2 et
