/*
 * This Jenkinsfile is for internal use
 */

pipeline {
  agent none
  options {
    retry(1)
    // This timeout can include wait time when executors are occupied, so using
    // something arbitrarily high for the whole pipeline
    timeout(time: 6, unit: 'HOURS')
    parallelsAlwaysFailFast()
  }

  stages {
    stage('Check') {
      agent { label 'rust' }
      steps {
        sh 'cargo fmt --check'
      }
    }

    stage('Build') {
      options {
        timeout(time: 1, unit: 'HOURS')
      }
      parallel {
        stage('Crates - FreeBSD') {
          agent { label 'freebsd' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j2 -C crates build'
          }
        }

        stage('Crates - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C crates build'
          }
        }

        stage('Lambdas - FreeBSD') {
          agent { label 'freebsd' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j2 -C lambdas build'
          }
        }

        stage('Lambdas - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C lambdas build'
          }
        }
      }
    }

    stage('Test') {
      options {
        timeout(time: 1, unit: 'HOURS')
      }
      parallel {
        stage('Crates Test - FreeBSD') {
          agent { label 'freebsd' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j2 -C crates test'
          }
        }

        stage('Crates Test - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C crates test'
          }
        }

        stage('Lambdas Test - Linux') {
          agent { label 'linux' }
          steps {
            sh './ci/setup.sh'
            sh 'gmake -j4 -C lambdas test'
          }
        }
      }
    }

    stage('Release') {
      failFast true
      when { branch 'main' }
      options {
        timeout(time: 2, unit: 'HOURS')
      }
      matrix {
        axes {
          axis {
            name 'PLATFORM'
            //values 'x86-64', 'arm64'
            values 'x86-64'
          }
          axis {
            name 'LAMBDA'
            values 'oxbow-lambda', 'sqs-ingest', 'file-loader', 'cdf-to-csv', 'group-events', 'auto-tag'
          }
        }
        stages {
          stage('Build') {
            // The zig builds don't work very well on FreeBSD
            agent { label 'linux' }
            steps {
              sh "cargo lambda build --${PLATFORM} --package ${LAMBDA} --lambda-dir target/lambda/${PLATFORM} --release --output-format zip"
              sh "mv target/lambda/${PLATFORM}/${LAMBDA}/bootstrap.zip target/lambda/${LAMBDA}-${PLATFORM}.zip"
              archiveArtifacts artifacts: "target/lambda/${LAMBDA}-${PLATFORM}.zip", fingerprint: true, onlyIfSuccessful: true
            }
          }
        }
      }
    }
  }
}

// vim: ft=groovy sw=2 ts=2 et
