[package]
name = "oxbow"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
chrono = { workspace = true }
deltalake = { workspace = true }
parquet = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
serde_json = "1.0"

dynamodb_lock = "0.6.1"
futures = "0.3.29"

[dev-dependencies]
fs_extra = "=1"
tempfile = "*"
tokio = { workspace = true }
criterion = "0.5"
parquet = "58.0"
